# Generated by Django 3.2 on 2022-05-28 15:01

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cover',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=account.models.image_profile_upload),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=account.models.image_profile_upload),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='seler_rank',
            field=models.CharField(choices=[('NEW SELER', 'NEW SELER'), ('L1 SELER', 'L1 SELER'), ('L2 SELER', 'L2 SELER'), ('BEST SELER', 'BEST SELER')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('WOMEN', 'WOMEN'), ('MEN', 'MEN')], max_length=10, null=True),
        ),
    ]
