# Generated by Django 3.2 on 2022-06-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profileuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='sex',
            new_name='gender',
        ),
    ]
