# Generated by Django 3.2 on 2022-06-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_sex_profileuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='bio',
        ),
    ]
