# Generated by Django 3.2 on 2022-08-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profileuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='brand',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
