# Generated by Django 3.2 on 2022-04-14 01:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_fr', models.CharField(max_length=50)),
                ('name_ar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_fr', models.CharField(max_length=50)),
                ('name_ar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='collection')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale', models.BooleanField(default=False)),
                ('stock_out', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image_card', models.ImageField(null=True, upload_to='')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''), blank=True, null=True, size=5)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=20)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=20)),
                ('category_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_child', to='store.categorychild')),
                ('category_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_parent', to='store.categoryparent')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_collection', to='store.collection')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='categorychild',
            name='category_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category_parent', to='store.categoryparent'),
        ),
    ]
