# Generated by Django 3.2 on 2022-04-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorychild',
            name='icon_dark',
            field=models.ImageField(null=True, upload_to='category/icons/child/dark'),
        ),
        migrations.AddField(
            model_name='categorychild',
            name='icon_light',
            field=models.ImageField(null=True, upload_to='category/icons/child/light'),
        ),
        migrations.AddField(
            model_name='categoryparent',
            name='icon_dark',
            field=models.ImageField(null=True, upload_to='category/icons/parent/dark'),
        ),
        migrations.AddField(
            model_name='categoryparent',
            name='icon_light',
            field=models.ImageField(null=True, upload_to='category/icons/parent/light'),
        ),
    ]
