# Generated by Django 3.2 on 2022-04-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220414_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorychild',
            name='icon_dark',
        ),
        migrations.RemoveField(
            model_name='categorychild',
            name='icon_light',
        ),
    ]
