# Generated by Django 3.2 on 2022-04-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220414_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryparent',
            name='name_ar',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='categoryparent',
            name='name_en',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='categoryparent',
            name='name_fr',
            field=models.CharField(max_length=30),
        ),
    ]
