# Generated by Django 3.2 on 2022-04-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220416_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryparent',
            name='name_ar',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='categoryparent',
            name='name_en',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='categoryparent',
            name='name_fr',
            field=models.CharField(max_length=25),
        ),
    ]
