# Generated by Django 3.2 on 2022-04-18 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220416_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_child', to='store.categorychild'),
        ),
    ]
