# Generated by Django 3.2 on 2022-04-19 01:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_card',
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=''), blank=True, null=True, size=10),
        ),
    ]
