# Generated by Django 3.2 on 2022-04-19 02:43

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220419_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image7', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image8', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image9', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('image10', models.ImageField(blank=True, null=True, upload_to=store.models.imageupload2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product')),
            ],
        ),
    ]
