# Generated by Django 3.2 on 2022-04-20 23:33

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220419_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=store.models.imageupload),
        ),
    ]
