# Generated by Django 3.2 on 2022-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220507_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
