# Generated by Django 3.2 on 2022-05-09 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_auto_20220508_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsResultInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allUserRate', models.FloatField(default=0)),
                ('stars5', models.FloatField(default=0)),
                ('stars4', models.FloatField(default=0)),
                ('stars3', models.FloatField(default=0)),
                ('stars2', models.FloatField(default=0)),
                ('stars1', models.FloatField(default=0)),
                ('starsPer5', models.FloatField(default=0)),
                ('starsPer4', models.FloatField(default=0)),
                ('starsPer3', models.FloatField(default=0)),
                ('starsPer2', models.FloatField(default=0)),
                ('starsPer1', models.FloatField(default=0)),
                ('allStars', models.FloatField(default=0)),
                ('reviews', models.FloatField(default=0)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductReviewsResultInfo', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueReview', models.CharField(default='unique key', max_length=1000000, unique=True)),
                ('stars', models.FloatField(default=1)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('seler_reponse', models.TextField(blank=True, max_length=500, null=True)),
                ('reviewDate', models.DateTimeField(auto_now=True)),
                ('reviewUpdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('reviewInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratting', to='store.reviewsresultinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ratting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
