# Generated by Django 3.2 on 2022-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productratting_reviewsresultinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allUserRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.FloatField(default=0),
        ),
    ]
