# Generated by Django 3.2 on 2022-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220509_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
    ]
