# Generated by Django 3.2 on 2022-05-16 16:27

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_saleper'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_guide_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.imageupload),
        ),
    ]
