# Generated by Django 3.2 on 2022-05-24 15:07

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_size_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to=store.models.imageupload),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_guide_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=store.models.imageupload),
        ),
    ]
