# Generated by Django 3.2 on 2022-06-12 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_auto_20220524_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
