# Generated by Django 3.2 on 2022-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productratting',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productratting',
            name='seler_reponse',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
