# Generated by Django 3.2 on 2022-07-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profileuser_bio'),
        ('store', '0021_auto_20220701_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='productratting',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_ratting', to='account.profileuser'),
        ),
    ]
