# Generated by Django 3.2 on 2022-07-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_productratting_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
