# Generated by Django 3.2 on 2022-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='score_stars',
            field=models.IntegerField(default=0),
        ),
    ]
