# Generated by Django 3.2 on 2022-07-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20220721_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='score_stars',
        ),
    ]
