# Generated by Django 3.2 on 2022-07-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_product_score_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score_stars',
            field=models.IntegerField(default=0),
        ),
    ]
