# Generated by Django 3.2 on 2022-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_productcolor_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score_search',
            field=models.IntegerField(default=0),
        ),
    ]
