# Generated by Django 3.2 on 2022-10-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product_score_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image9',
        ),
    ]
