# Generated by Django 3.2 on 2022-11-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20221028_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cache_en_delevery',
            field=models.BooleanField(default=True),
        ),
    ]
