# Generated by Django 3.2 on 2022-08-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0026_product_score_stars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=1000)),
                ('seler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_seler', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
