# Generated by Django 3.2 on 2022-08-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_product_score_stars'),
        ('account', '0005_remove_profileuser_bio'),
        ('chat', '0006_auto_20220810_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_seler', to='store.product'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_user', to='account.profileuser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_chat_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
