# Generated by Django 3.2 on 2022-08-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20220810_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='seler_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seler_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
