# Generated by Django 3.2 on 2022-08-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20220810_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='user',
            new_name='seler',
        ),
    ]
