# Generated by Django 3.2 on 2022-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_user_chatroom_seler'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='seler_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
