# Generated by Django 3.2 on 2022-08-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20220811_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
