# Generated by Django 3.2 on 2022-08-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheendelevry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cacheendelevry',
            name='logistics_tracking',
            field=models.CharField(choices=[('WITH_SELER', 'WITH_SELER'), ('WITH_DILIVER', 'WITH_DILIVER'), ('CLIENT_ACCEPTED', 'CLIENT_ACCEPTED'), ('CLIENT_RETURNED', 'CLIENT_RETURNED')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
