# Generated by Django 3.2 on 2022-08-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220815_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheendelevry',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
