# Generated by Django 3.2 on 2022-08-15 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_score_stars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_cacheendelevry_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CacheEnDelevry',
            new_name='CacheEnDelevery',
        ),
    ]
