# Generated by Django 3.2 on 2022-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_cacheendelevry_cacheendelevery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacheendelevery',
            name='products',
        ),
        migrations.AddField(
            model_name='cacheendelevery',
            name='products',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
