# Generated by Django 3.2 on 2022-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220817_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheendelevery',
            name='logistics_tracking',
            field=models.CharField(choices=[('WITH_SELER', 'WITH_SELER'), ('WITH_DILIVER', 'WITH_DILIVER'), ('CLIENT_ACCEPTED', 'CLIENT_ACCEPTED'), ('CLIENT_RETURNED', 'CLIENT_RETURNED')], default='WITH_SELER', max_length=100),
        ),
    ]
