# Generated by Django 3.2 on 2022-08-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0.0)),
                ('seler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seler_wallet', to='orders.wallet')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_wallet', to='orders.wallet')),
            ],
        ),
    ]
