# Generated by Django 3.2 on 2022-08-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_wallet'),
        ('orders', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='seler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seler_wallet', to='account.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_wallet', to='account.wallet'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
