# Generated by Django 3.2 on 2022-08-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220825_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
