# Generated by Django 3.2 on 2022-08-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_score_stars'),
        ('orders', '0012_usersales'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersales',
            name='cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersales',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='store.product'),
        ),
    ]
