# Generated by Django 3.2 on 2022-08-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_score_stars'),
        ('orders', '0013_auto_20220826_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersales',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='store.product'),
        ),
    ]
