# Generated by Django 3.2 on 2022-08-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_usersales_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersales',
            old_name='seler',
            new_name='seller',
        ),
    ]
