# Generated by Django 3.2 on 2022-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_seler_usersales_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersales',
            name='logistic',
            field=models.CharField(choices=[('WITH_SELER', 'WITH_SELER'), ('WITH_DILIVER', 'WITH_DILIVER'), ('CLIENT_ACCEPTED', 'CLIENT_ACCEPTED'), ('CLIENT_RETURNED', 'CLIENT_RETURNED')], default='WITH_SELER', max_length=100),
        ),
    ]
