# Generated by Django 3.2 on 2022-09-04 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_usersales_logistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersales',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
