# Generated by Django 3.2 on 2022-10-20 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0017_usersales_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=2000, null=True)),
                ('country', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('products', models.CharField(max_length=100000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('logistics_tracking', models.CharField(choices=[('WITH_SELER', 'WITH_SELER'), ('WITH_DILIVER', 'WITH_DILIVER'), ('CLIENT_ACCEPTED', 'CLIENT_ACCEPTED'), ('CLIENT_RETURNED', 'CLIENT_RETURNED')], default='WITH_SELER', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_paypal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
