# Generated by Django 3.2 on 2022-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderpaypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaypal',
            name='address',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='orderpaypal',
            name='city',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='orderpaypal',
            name='country',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='orderpaypal',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderpaypal',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderpaypal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
