# Generated by Django 3.2 on 2022-10-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20221020_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersales',
            name='order_paypal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user_paypal', to='orders.cacheendelevery'),
        ),
        migrations.AlterField(
            model_name='usersales',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user', to='orders.cacheendelevery'),
        ),
    ]
