# Generated by Django 3.2 on 2022-10-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20221020_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersales',
            name='order_paypal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user_paypal', to='orders.orderpaypal'),
        ),
    ]
